apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ng4ya83u9-go 
  janus-idp.io/tekton: ng4ya83u9-go
  backstage.io/kubernetes-id: ng4ya83u9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ng4ya83u9-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml